const prefix = 'auth/'
export enum AuthConstants {
  SET_IS_AUTH = prefix + 'SET_IS_AUTH',
  GET_AUTH_DATA = prefix + 'GET_AUTH_DATA',
  LOGOUT_FROM_ACCOUNT = prefix + 'LOGOUT_FROM_ACCOUNT',

  IS_FETHCHING_AUTH_DATA = prefix + 'IS_FETHCHING_AUTH_DATA',

  SET_PROFILE_INFO = prefix + 'SET_PROFILE_INFO',
  GET_PROFILE_INFO = prefix + 'GET_PROFILE_INFO',

  SET_RESPONSE_ERROR = prefix + 'SET_RESPONSE_ERROR',
  SET_FORM_ERROR = prefix + 'SET_FORM_ERROR',

  SET_AUTH_ERROR_MESSAGE = prefix + 'SET_AUTH_ERROR_MESSAGE',
}
