export enum AuthConstants {
  SET_IS_AUTH = 'SET_IS_AUTH',
  GET_AUTH_DATA = 'GET_AUTH_DATA',
  IS_FETHCHING_AUTH_DATA = 'IS_FETHCHING_AUTH_DATA',
  SET_AUTH_ERROR_MESSAGE = 'SET_AUTH_ERROR_MESSAGE',
  SET_PROFILE_INFO = 'SET_PROFILE_INFO',
  GET_PROFILE_INFO = 'GET_PROFILE_INFO',
}
